DROP TABLE players IF EXISTS;
CREATE TABLE players (
id INTEGER NOT NULL AUTO_INCREMENT,
user_Name VARCHAR(128) NOT NULL UNIQUE,
password VARCHAR (128) NOT NULL ,
PRIMARY KEY (id)
);

DROP TABLE games IF EXISTS;
CREATE TABLE games (
id INTEGER NOT NULL AUTO_INCREMENT,
title VARCHAR(128) NOT NULL,
author VARCHAR (128) NOT NULL,
number_Of_Players INTEGER NOT NULL,
game_Type VARCHAR (128),
PRIMARY KEY (id)
);

DROP TABLE venues IF EXISTS;
CREATE TABLE venues (
id INTEGER NOT NULL AUTO_INCREMENT,
name_Of_Venues VARCHAR(128) NOT NULL,
address VARCHAR(128) NOT NULL,
city VARCHAR(128) NOT NULL,
zip_Code VARCHAR(128) NOT NULL,
country VARCHAR (128) NOT NULL,
PRIMARY KEY (id)
);

DROP TABLE meetings IF EXISTS;
CREATE TABLE meetings (
id INTEGER NOT NULL AUTO_INCREMENT,
date_Of_Meeting VARCHAR(128) NOT NULL,
PRIMARY KEY (id)
);